### ISSUE TITLE
Dompdf\\Options::validateArtifactPath(): Argument #1 ($path) must be of type string, null given,

### ISSUE THREAD

**Issue by RizalFIrdaus** [barryvdh/laravel-dompdf#1042] opened 2024-04-15 04:10 UTC
After update laravel 10 and upgrade new version dompdf, we got error like this : 

Dompdf\\Options::validateArtifactPath(): Argument #1 ($path) must be of type string, null given,

if you have any solution, please reply this issues, thanks

**Comment by jason-nabooki** [comment] 2024-04-15 06:03
It looks like a bug in `dompdf/dompdf`. There's a PR for it - https://github.com/dompdf/dompdf/pull/3433

**Comment by eriqamiqo** [comment] 2024-04-15 06:43
ran into the same problem.

for the mean time, you can use the v2.0.4 of dompdf until this one has been sorted out.

`composer require dompdf/dompdf:2.0.4`

**Comment by moingeek** [comment] 2024-04-15 08:33
I ran into the same issue. But post downgrading to 2.0.4 version. It got sorted out.

**Comment by MitchGTV** [comment] 2024-04-15 09:26
I can confirm that downgrading to v2.0.4 has resolved this temporarily until the PR mentioned above is merged.

**Comment by jsncrdnl** [comment] 2024-04-15 09:40
🎊 
You saved my day, thanks !

**Closed** 2024-04-15 10:06 UTC
