### ISSUE TITLE
No block-level parent found. Not good.

### ISSUE THREAD

**Issue by ThunderBirdsX3** [barryvdh/laravel-dompdf#399] opened 2017-10-18 08:57 UTC
Laravel 5.4.36
PHP 7.1.10
laravel-dompdf 0.8.1

I got the problem when export pdf in my local server. With above spec.

But in my production is not get any error (PHP 7.1.8).

**Comment by bkilshaw** [comment] 2017-10-21 20:16
I ran into this same issue on an app running Laravel 5.4.28, PHP 7.1.10 and laravel-dompdf 0.8.1. Set up a blank install of laravel (5.5.18) and it's having the same issue as well.

I've narrowed it down to any html template that has a <head> block in it:

### Fails
```
<!DOCTYPE html>
<html>
<head>
    <title>Test</title>
</head>
<body>
    <h1>Test</h1>
</body>
</html>
```

### Works
```
<!DOCTYPE html>
<html>
<body>
    <h1>Test</h1>
</body>
</html>
```

**Comment by bkilshaw** [comment] 2017-10-21 20:31
This doesn't appear to be an issue with laravel-dompdf, it's goes back up to a problem with specific versions of libxml2. See here:

https://github.com/dompdf/dompdf/issues/1560

**Comment by bkilshaw** [comment] 2017-10-21 20:32
### For the record, it appears that removing all newlines from your code works:

Works
`<!DOCTYPE html><html><head><title>Test</title></head><body><h1>Test</h1></body></html>`

**Comment by taitai42** [comment] 2017-10-22 10:21
i have the same issue, 

for some really weird reason i can use any template as long as i put a `>` at the very beginning of the template. this is so strange

**Comment by anamikaswadesh** [comment] 2017-10-23 08:05
same issue
if  include css file it giving error otherwise perfect

**Comment by taitai42** [comment] 2017-10-23 08:10
actually this solution worked for me:  https://github.com/dompdf/dompdf/issues/1560#issuecomment-335106048

so basically just add ```$tag_names = array("html", "table", "tbody", "thead", "tfoot", "tr");
            foreach ($tag_names as $tag_name) {
                $nodes = $doc->getElementsByTagName($tag_name);

                foreach ($nodes as $node) {
                    self::removeTextNodes($node);
                }
            }``` after `   $doc->encoding = $encoding;` on line `492`

**Comment by taitai42** [comment] 2017-10-24 05:57
edit: actually this fix has been merged on master branch of dompdf after a pull request by epreston.

so if you use dev-master branch of dompdf you will have the fix...

**Comment by LasseRafn** [comment] 2017-10-26 13:10
I think it has been released 👍 

https://github.com/dompdf/dompdf/releases/tag/v0.8.1

**Comment by chrisbratherton** [comment] 2017-11-08 11:59
I am actually getting the same issue, PHP 7.0 & 7.1, DOMPDF 0.8.1. :(

I am using very very basic HTML and cannot see why or how this error is being thrown... I've tried all in the issues that I have found regarding the issue.

**Comment by danieluyo** [comment] 2017-11-08 18:51
Same

**Comment by ThunderBirdsX3** [comment] 2017-11-09 07:39
@chrisbratherton Try with php 7.1.8

**Comment by gazben** [comment] 2017-11-18 17:58
Same here.
Here is my workaraund:

```
        $pdf = app('dompdf.wrapper');
        $html = view('view.name', [
            'now' => Carbon::now()->format('Y.m.d H:i'),
        ]);
        $html = str_replace("\n", "", $html);
        $html = str_replace("\r", "", $html);
        $pdf->loadHTML($html);

        return $pdf->stream();
```

**Comment by lubber-de** [comment] 2017-11-22 16:09
To completely fix this directly in DomPDF when using PHP 7.1  i had to create a classwrapper (to not mess up which the composer package and the "self::removeTextNodes) addition in v0.8.1 did not help so far (i was using PHPExcel which probably broke the generated html when using php 7.1:

```php
class DOMPDF extends \Dompdf\Dompdf{
    public function __construct($options = null)
    {
        if ($options===null){
            $options = [];
        }
        if (is_array($options)) {
            $options = array_merge($options,[
                'isHtml5ParserEnabled' => true,
            ]);
        }
        parent::__construct($options);
    }
    public function loadHtml($str, $encoding = 'UTF-8')
    {
        $str = preg_replace('/>\s+</', '><', $str);
        parent::loadHtml($str, $encoding);
    }

}

```

**Comment by ThunderBirdsX3** [comment] 2017-12-07 05:10
Now this problem solve with https://github.com/dompdf/dompdf/releases/tag/v0.8.2

**Closed** 2017-12-07 05:10 UTC

**Comment by victor-priceputu** [comment] 2018-10-22 11:05
Had the same issue, for me it was caused by the `html` tag not being detected as a block-level parent.
Had to add the following CSS to fix it:
`html, body {
            display: block;
        }`
