### ISSUE TITLE
"No block-level parent found. Not good." error when using <head>

### ISSUE THREAD

**Issue by felixkiss** [barryvdh/laravel-dompdf#389] opened 2017-09-21 17:53 UTC
Hi,

I have run into a very strange issue that recently has caused my dompdf generation to fail with `No block-level parent found. Not good.`.

After debugging and consulting the other issues regarding this error on this issue tracker, I have figured out, that none of the causes mentioned (like using CSS or line breaks) are at fault in my setup, but rather the presence of a `<head>` section in my HTML.

It seems to me that this issue is somehow connected to my personal development environment, since it works fine in production or even on my coworker's machine. I have created the minimal breaking/working cases for reference: https://github.com/felixkiss/laravel-dompdf-issue/commit/38cf4a10f827c614a2ddbf8c90575d52faa1a9a9

![screen shot 2017-09-21 at 19 50 11](https://user-images.githubusercontent.com/256075/30710515-1fba444e-9f06-11e7-96ea-e6d3f3e2643c.png)
![screen shot 2017-09-21 at 19 50 18](https://user-images.githubusercontent.com/256075/30710517-23ff8352-9f06-11e7-82d5-3266fa77953a.png)

My working environment:
macOS 10.12.6
PHP 7.1.8
barryvdh/laravel-dompdf v0.8.1

Any help/hints on resolving would be much appreciated. It worked fine for the past 2 years and I don't know what to do next to resolve this (other than not using `<head>` which is not really an option since I rely on CSS styles, etc. that are defined there)

**Comment by kinnedev** [comment] 2017-09-25 12:56
I just ran into this issue as well! 

I am running Laravel Valet, but if I remove the head then it all works perfectly. 

I'll keep an eye on this thread and if I find any solution will post here

**Comment by Pauly-** [comment] 2017-09-25 14:32
I just encountered this error as well. It has been working before, but now the tests are not passing. I made several changes to my project, but will try to clone an older version of the repo to test if it could have anything to do with upgrading to L5.5. 

I will update this issue, if I figure out a solution.

**Comment by kinnedev** [comment] 2017-09-25 14:56
@Pauly- what are you running for a local env?

**Comment by Pauly-** [comment] 2017-09-25 15:06
I'm running Laravel Valet 2.0.5 and php 7.1.8

**Comment by burlap** [comment] 2017-09-26 08:17
The solution is to enable html5 parses. It's probably libxml issue. 

See this pull request https://github.com/barryvdh/laravel-dompdf/pull/384

And this issue in dompdf https://github.com/dompdf/dompdf/issues/1494

**Comment by Pauly-** [comment] 2017-09-26 13:02
@burlap I have enabled the html5 parser inside the config and it still doesn't work. For now I ended up striping away the whitespace between html tags.

**Comment by kinnedev** [comment] 2017-09-26 16:45
Dang! No luck with either approach. Hopefully I fix comes soon

**Comment by Pauly-** [comment] 2017-09-26 18:16
@kinnedev For reference, here is what I ended up doing:

```php
protected function makePdf()
{
    $html = View::make('path.to.pdf', ['data' => $data])->render();
    $html = preg_replace('/>\s+</', '><', $html);
    return PDF::loadHtml($html);
}

protected function savePdf()
{
    $pdf = $this->makePdf();
    Storage::disk('s3')->put('somedirectory/filename.pdf', $pdf->output());
}
```

**Comment by burlap** [comment] 2017-09-26 19:11
When this bug hit me, I was sure I had html5parser enabled until I checked it wasn't. You can make sure it works with
```php
$pdf->getDomPDF()->get_option('enable_html5_parser');

**Comment by Pauly-** [comment] 2017-09-26 20:12
@burlap I just tried checking as you mentioned. It surprisedly returned false even though the variable inside  `config/dompdf.php` has been set to true. 

However, I manually tried to overwriting the option like this:
```php
$pdf->getDomPDF()->set_option('enable_html5_parser', true);
```
It did not work either.. (the option was true, when checking)

Do you have some example code from your implementation?

**Comment by burlap** [comment] 2017-09-26 20:24
I don't know why set_option doesn't work, it's possible you are setting it after the html is already parsed. 

I've just changed the options in dompdf.php config file, as in #384 (in the pull request I've left the parser disabled, but obviously I have it enabled in my application), so what I have is this:

in config/dompdf.php
```php
"enable_html5_parser" => true,
```

to generate PDF download
```php
$pdf = PDF::loadView('some.template', ['options' => $options]);
return $pdf->download('document.pdf');

**Comment by Pauly-** [comment] 2017-09-26 20:39
@burlap Yes, it must have been the case. 

I added it to the config as you suggested and it did work. 

One thing I noticed is that the `DOMPDF_ENABLE_HTML5PARSER` key in the config should be `DOMPDF_ENABLE_HTML5_PARSER`. That's why it doesn't get set in the first place. I made a pull request for this.

**Comment by benabbottnz** [comment] 2017-09-26 21:25
This is so strange. I was working with this perfectly yesterday, and now today it's not working.

**Comment by daniescobedo** [comment] 2017-09-27 02:37
@benabbottnz Thanks it works for me!

**Comment by diegoflorez** [comment] 2017-09-29 22:05
Change lines 112 to 125 in **/vendor/barryvdh/laravel-dompdf/src/PDF.php**
From 
```php
    public function loadView($view, $data = array(), $mergeData = array(), $encoding = null){
        $html = $this->view->make($view, $data, $mergeData)->render();
        return $this->loadHTML($html, $encoding);
    }
```
To 
```php
    public function loadView($view, $data = array(), $mergeData = array(), $encoding = null){
        $html = $this->view->make($view, $data, $mergeData)->render();
        $html = preg_replace('/>\s+</', '><', $html);
        return $this->loadHTML($html, $encoding);
    }
```

**Comment by iamniwa** [comment] 2017-10-03 15:48
@diegoflorez Your solution is perfect to me. Thanks a lot !!

**Comment by barryvdh** [comment] 2017-10-04 07:13
Yeah I had to strip whitespace too, but only on PHP 7.1. Should be fixed in dompdf upstream.

**Closed by barryvdh** 2017-10-04 07:13 UTC

**Comment by LasseRafn** [comment] 2017-11-10 15:06
Based on the solution from @diegoflorez, I made a simple class with the same API:

``` php
namespace App\PDF;

class PDFViewHelper
{
	/**
	 * @param       $view
	 * @param array $data
	 * @param array $mergeData
	 * @param null  $encoding
	 *
	 * @return \PDF
	 */
	public static function loadView( $view, $data = [], $mergeData = [], $encoding = null ) {
		$html = view( $view, $data, $mergeData )->render();
		$html = preg_replace( '/>\s+</', '><', $html );

		return \PDF::loadHTML( $html, $encoding );
	}
}
```

So all you have to do is switch: `PDF::loadView(..)` out with `PDFViewHelper::loadView(..)`. Which is also a good thing, should you ever want to switch away from DOMPDF.

**Comment by xhava** [comment] 2018-01-25 20:42
@pactode your solution about change DOMPDF_ENABLE_HTML5_PARSER worked for me, thanks.

**Comment by silviolleite** [comment] 2018-01-29 19:23
The pactode solution works! Thanks ;)

**Comment by victor-priceputu** [comment] 2018-10-22 11:06
Had the same issue, for me it was caused by the `html` tag not being detected as a block-level parent.
Had to add the following CSS to fix it:
`html, body {
            display: block;
        }`

**Comment by NicksonYap** [comment] 2019-07-03 16:24
For my case, it was due to the use of 

```
      body {
        display: inline-block;
      }
```
The works:
```
      body {
        display: block;
      }
```

**Comment by IzaqueL95** [comment] 2023-03-16 13:16
I had the same problem, but the error was in <img> tag, when I commented this line everything worked, so I added in CSS img 
{display: block} and after it everything worked.
